### ISSUE TITLE
 请教问题

### ISSUE THREAD

**Issue by superBiuBiuMan** [realafei/cloud-disk-plugin#1]
大佬,看了你写的油猴脚本网盘文件批量重命名,代码写的很厉害,我也在学习大佬代码,我很好奇也很想知道您的怎么知道去应该在什么属性下获取那个文件列表的
比如夸克网盘,我想破脑袋也不知道会去从
pendingProps?.store?.getState?.()?.file?.listType

const originList = state.file?.[state.file.listType]?.list;
中获取文件列表,很想知道大佬你是怎么定位的

还有阿里云盘获取文件列表的操作代码也是,
node.pendingProps?.localStore?.listModel?.listModel;
希望大佬能够百忙之中解答下,先谢谢啦

**Comment by realafei** [comment]
在虚拟 dom 节点中找到所需要的数据确实会有点费功夫，
文件列表数据一般都会在 list、table 这类结构的组件中或 store 中，
在控制台中查看该 dom 节点挂载的 react 或 vue 虚拟节点属性，
react 中 pendingProps 代表传入组件的 props，
child sibling return 是其 子组件 兄弟组件 和父组件，
花点时间找到文件列表的数据，不是太难。

**Comment by superBiuBiuMan** [comment]
原来如此，感谢大佬的解答
